/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_a3;

import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class NovaTela extends javax.swing.JFrame {

    /**
     * Creates new form NovaTela
     */
    public NovaTela() {
        initComponents();
    }

    public JLabel getLblDado_1() {
        return lblDado_1;
    }

    public void setLblDado_1(JLabel lblDado_1) {
        this.lblDado_1 = lblDado_1;
    }

    public JLabel getLblDado_2() {
        return lblDado_2;
    }

    public void setLblDado_2(JLabel lblDado_2) {
        this.lblDado_2 = lblDado_2;
    }

    public JLabel getLblDado_3() {
        return lblDado_3;
    }

    public void setLblDado_3(JLabel lblDado_3) {
        this.lblDado_3 = lblDado_3;
    }

    public JLabel getLblDado_4() {
        return lblDado_4;
    }

    public void setLblDado_4(JLabel lblDado_4) {
        this.lblDado_4 = lblDado_4;
    }

    public JLabel getLblDado_5() {
        return lblDado_5;
    }

    public void setLblDado_5(JLabel lblDadp_5) {
        this.lblDado_5 = lblDado_5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbDado1 = new javax.swing.JRadioButton();
        jrbDado2 = new javax.swing.JRadioButton();
        jrbDado3 = new javax.swing.JRadioButton();
        jrbDado4 = new javax.swing.JRadioButton();
        jrbDado5 = new javax.swing.JRadioButton();
        btnRelancar = new javax.swing.JButton();
        lblDado_1 = new javax.swing.JLabel();
        lblDado_2 = new javax.swing.JLabel();
        lblDado_3 = new javax.swing.JLabel();
        lblDado_4 = new javax.swing.JLabel();
        lblDado_5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbDado1.setText("Dado 1");
        jrbDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDado1ActionPerformed(evt);
            }
        });

        jrbDado2.setText("Dado 2");
        jrbDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDado2ActionPerformed(evt);
            }
        });

        jrbDado3.setText("Dado 3");
        jrbDado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDado3ActionPerformed(evt);
            }
        });

        jrbDado4.setText("Dado 4");
        jrbDado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDado4ActionPerformed(evt);
            }
        });

        jrbDado5.setText("Dado 5");
        jrbDado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDado5ActionPerformed(evt);
            }
        });

        btnRelancar.setText("Rejogar");
        btnRelancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbDado1)
                    .addComponent(btnRelancar)
                    .addComponent(jrbDado5)
                    .addComponent(jrbDado4)
                    .addComponent(jrbDado3)
                    .addComponent(jrbDado2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDado_1)
                        .addComponent(lblDado_2)
                        .addComponent(lblDado_3))
                    .addComponent(lblDado_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDado_5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDado1)
                    .addComponent(lblDado_1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDado2)
                    .addComponent(lblDado_2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDado3)
                    .addComponent(lblDado_3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDado4)
                    .addComponent(lblDado_4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDado5)
                    .addComponent(lblDado_5))
                .addGap(68, 68, 68)
                .addComponent(btnRelancar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelancarActionPerformed
        if (btnRelancar.isEnabled()){
            setVisible(false);
        }
    }//GEN-LAST:event_btnRelancarActionPerformed

    private void jrbDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDado1ActionPerformed
        if (jrbDado1.isSelected()){
            Random random = new Random();
            int dados1 = random.nextInt(6)+1;
            String dado1 = Integer.toString(dados1);
            lblDado_1.setText(dado1);
        }    
    }//GEN-LAST:event_jrbDado1ActionPerformed

    private void jrbDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDado2ActionPerformed
        if (jrbDado2.isSelected()){
            Random random = new Random();
            int dados2 = random.nextInt(6)+1;
            String dado2 = Integer.toString(dados2);
            lblDado_2.setText(dado2);
        }
    }//GEN-LAST:event_jrbDado2ActionPerformed

    private void jrbDado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDado3ActionPerformed
        if (jrbDado3.isSelected()){
            Random random = new Random();
            int dados3 = random.nextInt(6)+1;
            String dado3 = Integer.toString(dados3);
            lblDado_3.setText(dado3);
        }
    }//GEN-LAST:event_jrbDado3ActionPerformed

    private void jrbDado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDado4ActionPerformed
        if (jrbDado4.isSelected()){
            Random random = new Random();
            int dados4 = random.nextInt(6)+1;
            String dado4 = Integer.toString(dados4);
            lblDado_4.setText(dado4);
        }    
    }//GEN-LAST:event_jrbDado4ActionPerformed

    private void jrbDado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDado5ActionPerformed
        if (jrbDado5.isSelected()){
            Random random = new Random();
            int dados5 = random.nextInt(6)+1;
            String dado5 = Integer.toString(dados5);
            lblDado_5.setText(dado5);
        }
    }//GEN-LAST:event_jrbDado5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelancar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbDado1;
    private javax.swing.JRadioButton jrbDado2;
    private javax.swing.JRadioButton jrbDado3;
    private javax.swing.JRadioButton jrbDado4;
    private javax.swing.JRadioButton jrbDado5;
    private javax.swing.JLabel lblDado_1;
    private javax.swing.JLabel lblDado_2;
    private javax.swing.JLabel lblDado_3;
    private javax.swing.JLabel lblDado_4;
    private javax.swing.JLabel lblDado_5;
    // End of variables declaration//GEN-END:variables

    
}
